apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  # required by argocd
  app.kubernetes.io/name: argocd-server
  app.kubernetes.io/component: server
