apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - rbac/
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: strimzi
  domain: apps
  feature: kafka
  group: operators
