apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
data:
  # local users
  # accounts.andy: login
  # accounts.adam: login
  # accounts.joerg: login
  # accounts.paolo: login

  # repositories
  repositories: |
    - url: https://gitlab.com/sbt-devops/ci-cd/cicd-devops.git
    - url: https://gitlab.com/sbt-devops/devops.git
    - url: https://gitlab.com/sbt-data-ingestion-engine/die-devops.git
    - url: https://gitlab.com/sbt-data-ingestion-engine/historical-data-provider/hdp-devops.git
    - url: https://gitlab.com/sbt-data-ingestion-engine/market-state/mst-devops.git
  repository.credentials: |
    - url: https://gitlab.com/sbt-devops
      usernameSecret:
        name: gitlab-cd-creds
        key: username
      passwordSecret:
        name: gitlab-cd-creds
        key: password
    - url: https://gitlab.com/sbt-data-ingestion-engine
      usernameSecret:
        name: gitlab-cd-creds
        key: username
      passwordSecret:
        name: gitlab-cd-creds
        key: password
