apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: in-cluster
spec:
  description: Project related to CI/CD in-cluster (ceiba-platform-cicd)
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
  orphanedResources:
      warn: true
