apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - default.yaml
  - in-cluster.yaml

commonLabels:
  app: argocd
  domain: gitops
  group: projects
  # required by argocd
  app.kubernetes.io/part-of: argocd

commonAnnotations:
  managed-by: argocd.argoproj.io
  argoCDVersion: "2.0.3"
