apiVersion: v1
kind: ConfigMap
metadata:
  name: http-server-db
data:
  # logging
  LOG_ENCODING: json

  # tracing
  JAEGER_SERVICE_NAME: http-server-db
  JAEGER_SAMPLER_TYPE: const
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_REPORTER_LOG_SPANS: "true"
  JAEGER_REPORTER_FLUSH_INTERVAL: 1s
  JAEGER_AGENT_PORT: "6831"
  JAEGER_AGENT_HOST: jaeger-agent.tracing.svc.cluster.local

  # database
  DB_HOST: postgres.apps.svc.cluster.local
  # DB_PORT: "5432"
  # TODO replace following config with values from postgresql configmap and secret
  DB_USERNAME: postgres
  DB_PASSWORD: supersecret
  DB_NAME: postgres
