
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 10_crds/
  - 20_operator/
  - 30_ns-rbac/
  - 40_prometheus/

commonLabels:
  domain: monitoring
  feature: prometheus
