
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - 10_crds/
  - 20_operator/
  - 30_kafka/
  - 40_topics/
  - 50_monitoring/

commonLabels:
  domain: apps
  feature: kafka
