
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - serviceAccount.yaml
  - clusterRole.yaml
  - clusterRoleBinding.yaml
  - deployment.yaml
  - service.yaml
  - serviceMonitor.yaml

commonLabels:
  app: prometheus-operator
  group: operators
  component: controller

commonAnnotations:
  version: v0.44.0
