apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # using ArgoCD sync-wave feature to deploy in this exact order
  - jaeger.yaml

commonLabels:
  domain: tracing
  group: apps
