apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: strimzi-cluster-operator
spec:
  selector:
    matchLabels:
      app: strimzi
      domain: broker
      feature: kafka
      group: operators
      component: cluster-operator
  endpoints:
    - port: http
      interval: 15s
      scrapeTimeout: 14s
