apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: strimzi-cluster-operator
spec:
  selector:
    matchLabels:
      app: strimzi
      domain: apps
      feature: kafka
      group: operators
  endpoints:
    - port: http
      interval: 15s
      scrapeTimeout: 14s
