apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  labels:
    feature: loki
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: in-cluster
  source:
    repoURL: https://github.com/bygui86/workshop-tage-2021
    targetRevision: master
    path: infrastructure/40_logging/10_loki
  destination:
    name: in-cluster
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=background
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
