
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jaeger.yaml
  - service.yaml
  - svc-monitor.yaml

# WARN: replaced by transformer "kustomization_label-transformer.yaml"
# commonLabels:

transformers:
  - kustomization_label-transformer.yaml

commonAnnotations:
  version: "1.21.0"
