
# see:
#   - https://github.com/kubernetes-sigs/kustomize/issues/2034#issuecomment-673079108
#   - https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#labels-transformer

apiVersion: builtin
kind: LabelTransformer
metadata:
  name: notImportantHere
labels:
  app: jaeger
  domain: tracing
  feature: jaeger
fieldSpecs:
  - path: metadata/labels
    create: true
