apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - secret.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - svc-monitor.yaml

commonLabels:
  app: postgresql
  domain: apps
  group: databases

commonAnnotations:
  version: "13.1"
  exporterVersion: "v0.8.0"
