apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
      domain: apps
      group: databases
      headless: "false"
  namespaceSelector:
    matchNames:
      - apps
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 29s
