
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - alertmanager.yaml
  - alertmanagerConfig.yaml
  - podmonitor.yaml
  - probe.yaml
  - prometheus.yaml
  - prometheusrule.yaml
  - servicemonitor.yaml
  - thanosruler.yaml

commonLabels:
  app: prometheus-operator
  group: crds

commonAnnotations:
  version: v0.44.0
